
project_root: "/kaggle/working/Group-Activity-Recognition"
root: "/kaggle" 

experiment:
  name_person_activity: "PersonActivity_Classifier_B3"
  name_group_activity: "GroupActivity_Classifier_B3"
  version: "1.0"
  output_dir: "modeling/experiments" 

system:
  seed: 42 
  num_workers: 4 

data:
  videos_path: "/kaggle/input/group-activity-recognition-volleyball/videos"
  annot_path: "/kaggle/input/group-activity-recognition-volleyball/annot_all.pkl"
  video_splits:
    train: ['1', '3', '6', '7', '10', '13', '15', '16', '18', '22', '23', '31', '32', '36', '38', '39', '40', '41', '42', '48', '50', '52', '53', '54']
    validation: ['0', '2', '8', '12', '17', '19', '24', '26', '27', '28', '30', '33', '46', '49', '51']
    test: ['4', '5', '9', '11', '14', '20', '21', '25', '29', '34', '35', '37', '43', '44', '45', '47']

dataset:
  num_classes:
    person_activity: 9
    group_activity: 8
  label_classes:
    person_activity: ["waiting", "setting", "digging", "falling", "spiking", "blocking", "jumping", "moving", "standing"]
    group_activity: ["r_set", "r_spike", "r-pass", "r_winpoint", "l_winpoint", "l-pass", "l-spike", "l_set"]


training:
  patience: 10
  learning_rate: 0.0001
  optimizer: "AdamW" 
  epochs: 10
  log_interval: 50 

  person_activity:
    batch_size: 128
    weight_decay: 0.01
    label_smoothing: 0.1     
  
  group_activity:
    batch_size: 32
    weight_decay: 0.01
    label_smoothing: 0.1 
